select substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,BLAZE_TAG_NAME_DESC as Click_Tag, 
sum(VWR_INTERACTION) as VWR_Clickthrough from TFR_REP.INTERACTION_DETAIL_MV WHERE IO_ID = {0} and BLAZE_ACTION_TYPE_DESC = 'Click-thru' 
AND TO_CHAR(DAY_DESC, 'YYYY-MM-DD') BETWEEN '{1}' AND '{2}'
GROUP BY PLACEMENT_ID, PLACEMENT_DESC, BLAZE_TAG_NAME_DESC ORDER BY PLACEMENT_ID