select substr(OVERALL.PLACEMENT_DESC,1,INSTR(OVERALL.PLACEMENT_DESC, '.', 1)-1) as Placement#, MEDIA_SIZE_DESC as Adsize, sum(VIEWS) as Delivered_Impression, sum(CLICKS) as Clicks, 
sum(CONVERSIONS) as Conversion 
from TFR_REP.ADSIZE_SALES_MV WHERE IO_ID = {0} AND TO_CHAR(DAY_DESC, 'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' GROUP BY PLACEMENT_ID,PLACEMENT_DESC, MEDIA_SIZE_DESC ORDER BY PLACEMENT_ID