SELECT substr(PLACEMENT_DESC,1,INSTR(PLACEMENT_DESC, '.', 1)-1) as Placement#,
sum(DPE_INTERACTIVE_ENGAGEMENTS) as DpeIntractiveEngagements,
sum(ENG_INTERACTIVE_ENGAGEMENTS) as EngIntractiveEngagements,
sum(ENG_TOTAL_TIME_SPENT) as Engtotaltimespent,sum(DPE_TOTAL_TIME_SPENT) as Dpetotaltimespent 
from TFR_REP.KEY_METRIC_MV WHERE IO_ID = {0} AND TO_CHAR(TO_DATE(DAY_DESC, 'MM/DD/YYYY'),'YYYY-MM-DD') BETWEEN '{1}' AND '{2}' 
GROUP BY PLACEMENT_ID, PLACEMENT_DESC ORDER BY PLACEMENT_ID